from typing import Protocol
import numpy as np

class Instrument(Protocol):
    def note_on(self, note: int, velocity: int) -> None: ...
    def note_off(self, note: int) -> None: ...
    def render(self, frames: int) -> np.ndarray: ...
    def num_active_voices(self) -> int: ...
