from typing import Protocol
import numpy as np

class Voice(Protocol):
    def note_off(self) -> None: ...
    def finished(self) -> bool: ...
    def render(self, frames: int, sr: int) -> np.ndarray: ...

class FrequencyInstrument(Protocol):
    def note_on(self, freq_hz: float, velocity: int) -> None: ...
    def note_off(self, freq_hz: float) -> None: ...
    def cc(self, control: int, value: int) -> None: ...
    def render(self, frames: int, sr: int) -> np.ndarray: ...
    def num_active_voices(self) -> int: ...

class MidiInstrument(Protocol):
    def note_on(self, note: int, velocity: int) -> None: ...
    def note_off(self, note: int) -> None: ...
    def cc(self, control: int, value: int) -> None: ...
    def render(self, frames: int, sr: int) -> np.ndarray: ...
    def num_active_voices(self) -> int: ...